service: barkhaus-lambda # NOTE: update this with your service name

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  timeout: 300

functions:
  getClients:
    handler: clients/getClients.getClients
    events:
      - http:
          path: Clients
          method: get

  getClient:
    handler: clients/getClient.getClient
    events:
      - http:
          path: Clients/{ClientID}
          method: get

  deleteClient:
    handler: clients/deleteClient.deleteClient
    events:
      - http:
          path: Clients/{ClientID}
          method: delete

  createClient:
    handler: clients/createClient.createClient
    events:
      - http:
          path: Clients
          method: post                 