service: barkhaus-lambda # NOTE: update this with your service name

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  timeout: 300

functions:
  getDogs:
    handler: Dogs/getDogs.getDogs
    events:
      - http:
          path: Dogs
          method: get

  getDog:
    handler: Dogs/getDog.getDog
    events:
      - http:
          path: Dogs/{DogID}
          method: get

  deleteDog:
    handler: Dogs/deleteDog.deleteDog
    events:
      - http:
          path: Dogs/{DogID}
          method: delete

  createDog:
    handler: Dogs/createDog.createDog
    events:
      - http:
          path: Dogs
          method: post

  updateDog:
    handler: Dogs/updateDog.updateDog
    events:
      - http:
          path: Dogs/{DogID}
          method: patch
          
          